name: Test

on:
  push:
  workflow_dispatch:
    inputs:
      django:
        description: 'pip-installable package or git repository URL'
        required: true
        default: 'git+https://github.com/django/django.git@main#egg=Django'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        django:
          # Latest stable Django release
          - "Django"
          # Django 5.2.x branch
          - "git+https://github.com/django/django.git@stable/5.2.x#egg=Django"
          # PR to reduce the number of bulk queries executed by the ORM
          - "git+https://github.com/laymonage/django.git@ticket_36143#egg=Django"
          # PR to fix eager SQL formatting that slows down assertNumQueries
          - "git+https://github.com/nessita/django.git@ticket-36380-take-2#egg=Django"
          # Custom input, defaults to the main branch of the Django repository
          - ${{ inputs.django ||'git+https://github.com/django/django.git@main#egg=Django' }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "${{ matrix.django }}"
      - name: Test
        run: |
          python manage.py test
